GPX_NAMESPACE = "{http://www.topografix.com/GPX/1/1}"
TRK_ELEMENT = f"{GPX_NAMESPACE}trk"
TRKSEG_ELEMENT = f"{GPX_NAMESPACE}trkseg"
TRKPT_ELEMENT = f"{GPX_NAMESPACE}trkpt"
ELE_ELEMENT = f"{GPX_NAMESPACE}ele"
TIME_ELEMENT = f"{GPX_NAMESPACE}time"
EXTENSIONS_ELEMENT = f"{GPX_NAMESPACE}extensions"
GARMIN_EXTENSIONS_ELEMENT = "{http://www.garmin.com/xmlschemas/TrackPointExtension/v1}"
